# Generated by Django 5.2.5 on 2025-08-14 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('glass_type', models.CharField(blank=True, max_length=80, null=True)),
                ('flavor_scale', models.PositiveSmallIntegerField()),
                ('invention_year', models.SmallIntegerField(blank=True, null=True)),
                ('description_short', models.TextField(blank=True, null=True)),
                ('story_long', models.TextField(blank=True, null=True)),
                ('time_to_make_sec', models.IntegerField(default=0)),
                ('price_auto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('archived', 'archived')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cocktails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.SmallIntegerField(default=1)),
                ('amount_oz', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('unit_input', models.CharField(max_length=32)),
                ('amount_input', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('prep_note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_optional', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cocktail_ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CocktailSummary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=140)),
                ('name', models.CharField(max_length=255)),
                ('glass_type', models.CharField(max_length=80, null=True)),
                ('flavor_scale', models.PositiveSmallIntegerField()),
                ('invention_year', models.SmallIntegerField(null=True)),
                ('description_short', models.TextField(null=True)),
                ('story_long', models.TextField(null=True)),
                ('time_to_make_sec', models.IntegerField()),
                ('abv_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('price_suggested', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('allergens_json', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'cocktail_summary_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('abv_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cost_per_oz', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('is_housemade', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('labor_cost_per_hour', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('overhead_pct', models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ('price_round_increment', models.DecimalField(decimal_places=3, default=0.25, max_digits=6)),
            ],
            options={
                'db_table': 'settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('to_oz_factor', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('non_volumetric', models.BooleanField(default=False)),
                ('oz_equivalent', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CocktailABV',
            fields=[
                ('cocktail', models.OneToOneField(db_column='cocktail_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='abv_row', serialize=False, to='cocktails.cocktail')),
                ('abv_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'cocktail_abv_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CocktailAllergens',
            fields=[
                ('cocktail', models.OneToOneField(db_column='cocktail_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='allergen_row', serialize=False, to='cocktails.cocktail')),
                ('allergens_json', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'cocktail_allergens_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CocktailPrice',
            fields=[
                ('cocktail', models.OneToOneField(db_column='cocktail_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='price_row', serialize=False, to='cocktails.cocktail')),
                ('price_raw', models.DecimalField(decimal_places=6, max_digits=12)),
                ('price_rounded', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
            options={
                'db_table': 'cocktail_price_v',
                'managed': False,
            },
        ),
    ]
